# Generated by Django 5.2.4 on 2025-07-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('caller_name', models.CharField(max_length=255)),
                ('caller_number', models.CharField(max_length=20)),
                ('call_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('call_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='backend.calllog')),
            ],
        ),
    ]
