# Generated by Django 5.2.4 on 2025-07-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_conversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='ai_response',
            new_name='full_transcript',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_input',
        ),
    ]
