# Generated by Django 5.2.4 on 2025-07-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_ai_response_conversation_full_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='initial_findings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
